---
- hosts: openldap_servers
  become: yes
  become_method: sudo
  roles:
  - role: bennojoy.openldap_server
    openldap_server_domain_name: example.com
    openldap_server_rootpw: zeus
    openldap_server_enable_ssl: false

  - role: net2grid.openldap_config
    default_user_password: nucar
    openldap_create_organizationalunits:
      - Groups
      - People
      - Hosts
    openldap_create_users:
      - name: cmccardwell
        cn: Carter McCardwell
        sn: McCardwell
        password: nucar
        email: cmccardwell
        group_ou: ou=People
