- hosts: slurm_server
  become: yes
  become_method: sudo
  roles:
  - role: 'indigo_dc.slurm'
    slurm_type_of_node: 'front'
    slurm_server_name: pantheon-pi
    slurm_wn_nodenames: [pantheon-0, pantheon-1, pantheon-2, pantheon-3]

- hosts: slurm_worknodes
  become: yes
  become_method: sudo
  roles:
  - role: 'indigo_dc.slurm'
    slurm_type_of_node: 'wn'
    slurm_server_name: pantheon-pi
