---
- hosts: all
  become: yes
  become_method: sudo
  vars_files:
    - user-vars.yml
  tasks:
  - name: Create users.
    user:
      name: "{{ item.name }}"
      comment: "{{ item.fullname }}"
      createhome: yes
      groups: "{{ item.groups }}"
      uid: "{{ item.uid }}"
      shell: /bin/bash
      password: "{{ item.password }}"
    with_items:
    - "{{ users }}"

  - name: Create user SSH keys.
    user:
      name: "{{ item.name }}"
      generate_ssh_key: yes
    run_once: yes
    delegate_to: pantheon-pi
    with_items:
    - "{{ users }}"
  
  - name: Modify SSH directory to allow temporary reading of keys.
    file:
      name: "/home/{{ item.name }}/.ssh"
      state: directory
      owner: "{{ item.name }}"
      group: sudo
      mode: 0755
    with_items:
    - "{{ users }}"

  - name: Modify SSH keys to allow temporary reading of keys.
    file:
      name: "/home/{{ item[0].name }}/.ssh/{{ item[1] }}"
      state: file
      owner: "{{ item[0].name }}"
      group: sudo
      mode: 0755
    run_once: yes
    delegate_to: pantheon-pi
    with_nested:
      - "{{ users }}"
      - ["id_rsa", "id_rsa.pub"]

  - name: Add user SSH keys to user authorized keys.
    authorized_key:
      user: "{{ item.name }}"
      state: present
      key:  "{{ lookup('file', '/home/{{ item.name }}/.ssh/id_rsa.pub') }}"
    with_items:
    - "{{ users }}"

  - name: Copy SSH keys to nodes.
    copy:
      src: "/home/{{ item[0].name }}/.ssh/{{ item[1] }}"
      dest: "/home/{{ item[0].name }}/.ssh/{{ item[1] }}"
      owner: "{{ item[0].name }}"
      group: sudo
      mode: 0600
    with_nested:
      - "{{ users }}"
      - ["id_rsa", "id_rsa.pub"]

  - name: Reset SSH directory permissions.
    file:
      name: "/home/{{ item.name }}/.ssh"
      state: directory
      owner: "{{ item.name }}"
      group: sudo
      mode: 0700
    run_once: yes
    with_items:
    - "{{ users }}"
