---
- hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Install gfortran packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - gfortran-5
    - name: Install numactl for Nvidia binary CPU pinning
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - numactl
