---
# This playbook is based off of:
# https://github.com/bennojoy/openldap_server
# https://github.com/net2grid/ansible-openldap_config
# copyright Tristan Sweeney 2017
- hosts: openldap_servers
  become: yes
  become_method: sudo
  roles:
  - role: bennojoy.openldap_server
    openldap_server_domain_name: pantheon.ece.neu.edu
    openldap_server_rootpw: zeus
    openldap_server_enable_ssl: false

  - role: net2grid.openldap_config
    default_user_password: nucar
    openldap_create_organizationalunits:
      - Groups
      - People
      - Hosts
    openldap_create_users:
      - name: tsweeney
        cn: Tristan Sweeney
        sn: Sweeney
        password: nucar
        email: sweeney.tr@husky.neu.edu
        group_ou: ou=People
